/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Disp.h>
#include <Up_aliases.h>
#include <Up.h>
#include <Down_aliases.h>
#include <Down.h>
#include <pinStart_aliases.h>
#include <pinStart.h>
#include <But_Reg.h>
#include <Cont_Reg.h>
#include <Pin_Up_aliases.h>
#include <Pin_Up.h>
#include <Pin_Down_aliases.h>
#include <Pin_Down.h>
#include <Clock_1.h>
#include <Menu_aliases.h>
#include <Menu.h>
#include <Back_aliases.h>
#include <Back.h>
#include <LED_Up_aliases.h>
#include <LED_Up.h>
#include <LED_Down_aliases.h>
#include <LED_Down.h>
#include <Disp_LCDPort_aliases.h>
#include <Disp_LCDPort.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

